safe: false
auto: false
server: false
server_port: 4000

source: .
destination: ./_site
plugins: ./_plugins

future: true
lsi: false
pygments: true
markdown: maruku
permalink: date

maruku:
  use_tex: true
  use_divs: true
  png_engine: blahtex
  png_dir: images/latex
  png_url: /images/latex
